In [1]:
import pandas as pd
import numpy as np

tickers = pd.read_excel(r"C:\Users\naksh\Projects\xgboost_stock_ranking\data\raw\ind_nifty100list.xlsx",
 sheet_name = "ind_nifty100list",
  usecols="F",
   skiprows=0,
    nrows=104
)
tickers = tickers["Ticker"].tolist()
print(tickers)

['ABB.NS', 'ADANIENSOL.NS', 'ADANIENT.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'DMART.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BAJAJHLDNG.NS', 'BANKBARODA.NS', 'BEL.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BOSCHLTD.NS', 'BRITANNIA.NS', 'CGPOWER.NS', 'CANBK.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'COALINDIA.NS', 'CUMMINSIND.NS', 'DLF.NS', 'DIVISLAB.NS', 'DRREDDY.NS', 'DUMMYVEDL1.NS', 'DUMMYVEDL2.NS', 'DUMMYVEDL3.NS', 'DUMMYVEDL4.NS', 'EICHERMOT.NS', 'ETERNAL.NS', 'GAIL.NS', 'GODREJCP.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCAMC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HINDALCO.NS', 'HAL.NS', 'HINDUNILVR.NS', 'HINDZINC.NS', 'HYUNDAI.NS', 'ICICIBANK.NS', 'ITC.NS', 'INDHOTEL.NS', 'IOC.NS', 'IRFC.NS', 'INFY.NS', 'INDIGO.NS', 'JSWSTEEL.NS', 'JINDALSTEL.NS', 'JIOFIN.NS', 'KOTAKBANK.NS', 'LTM.NS', 'LT.NS', 'LODHA.NS', 'M&M.NS', 'MARUTI.NS', 'MAXHEALTH.NS', 'MAZDOCK.NS', 'MUTHOOTFIN.NS', 'NTPC.NS', 'NESTLEIND.NS', 'ONGC.NS', 'PIDILITIND.NS', 'PFC.NS', 'POWERGRID.NS', 'PNB.NS', 'RECLTD.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'MOTHERSON.NS', 'SHREECEM.NS', 'SHRIRAMFIN.NS', 'ENRIN.NS', 'SIEMENS.NS', 'SOLARINDS.NS', 'SBIN.NS', 'SUNPHARMA.NS', 'TVSMOTOR.NS', 'TATACAP.NS', 'TCS.NS', 'TATACONSUM.NS', 'TMCV.NS', 'TMPV.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TRENT.NS', 'ULTRACEMCO.NS', 'UNIONBANK.NS', 'UNITDSPR.NS', 'VBL.NS', 'VEDL.NS', 'WIPRO.NS', 'ZYDUSLIFE.NS']

In [2]:
import yfinance as yf
from pathlib import Path
raw_data = yf.download(
    tickers=tickers,
    start="2015-01-01",
    end="2025-01-01",
    auto_adjust=True,
    progress=True,
    group_by="ticker"
)

[*********             18%                       ]  19 of 104 completed$TATACAP.NS: possibly delisted; no price data found  (1d 2015-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1420050600, endDate = 1735669800")
[*******************   40%                       ]  42 of 104 completed$ENRIN.NS: possibly delisted; no price data found  (1d 2015-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1420050600, endDate = 1735669800")
[********************  42%                       ]  44 of 104 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DUMMYVEDL1.NS"}}}
[**********************45%                       ]  47 of 104 completed$DUMMYVEDL1.NS: possibly delisted; no timezone found
[**********************65%******                 ]  68 of 104 completed$TMCV.NS: possibly delisted; no price data found  (1d 2015-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1420050600, endDate = 1735669800")
[**********************88%*****************      ]  91 of 104 completed$DUMMYVEDL2.NS: possibly delisted; no timezone found
[**********************88%*****************      ]  92 of 104 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: DUMMYVEDL3.NS"}}}
[**********************97%********************** ]  101 of 104 completed$DUMMYVEDL4.NS: possibly delisted; no timezone found
[**********************98%********************** ]  102 of 104 completed$DUMMYVEDL3.NS: possibly delisted; no timezone found
[*********************100%***********************]  104 of 104 completed

7 Failed downloads:
['TATACAP.NS', 'ENRIN.NS', 'TMCV.NS']: possibly delisted; no price data found  (1d 2015-01-01 -> 2025-01-01) (Yahoo error = "Data doesn't exist for startDate = 1420050600, endDate = 1735669800")
['DUMMYVEDL1.NS', 'DUMMYVEDL2.NS', 'DUMMYVEDL4.NS', 'DUMMYVEDL3.NS']: possibly delisted; no timezone found

In [3]:
raw_data.shape

(2467, 527)

In [4]:
raw_data.columns

MultiIndex([(  'HDFCLIFE.NS',      'Open'),
            (  'HDFCLIFE.NS',      'High'),
            (  'HDFCLIFE.NS',       'Low'),
            (  'HDFCLIFE.NS',     'Close'),
            (  'HDFCLIFE.NS',    'Volume'),
            ('MUTHOOTFIN.NS',      'Open'),
            ('MUTHOOTFIN.NS',      'High'),
            ('MUTHOOTFIN.NS',       'Low'),
            ('MUTHOOTFIN.NS',     'Close'),
            ('MUTHOOTFIN.NS',    'Volume'),
            ...
            ('DUMMYVEDL4.NS',       'Low'),
            ('DUMMYVEDL4.NS',     'Close'),
            ('DUMMYVEDL4.NS', 'Adj Close'),
            ('DUMMYVEDL4.NS',    'Volume'),
            ('DUMMYVEDL3.NS',      'Open'),
            ('DUMMYVEDL3.NS',      'High'),
            ('DUMMYVEDL3.NS',       'Low'),
            ('DUMMYVEDL3.NS',     'Close'),
            ('DUMMYVEDL3.NS', 'Adj Close'),
            ('DUMMYVEDL3.NS',    'Volume')],
           names=['Ticker', 'Price'], length=527)

In [5]:
raw_data.to_csv(r"C:\Users\naksh\Projects\xgboost_stock_ranking\data\raw\nifty100_daily.csv")

In [6]:
raw_data.head()

Ticker     HDFCLIFE.NS                       MUTHOOTFIN.NS              \
Price             Open High Low Close Volume          Open        High
Date
2015-01-01         NaN  NaN NaN   NaN    NaN    157.411502  174.036082
2015-01-02         NaN  NaN NaN   NaN    NaN    173.875414  173.875414
2015-01-05         NaN  NaN NaN   NaN    NaN    163.836453  165.041133
2015-01-06         NaN  NaN NaN   NaN    NaN    155.684778  158.776782
2015-01-07         NaN  NaN NaN   NaN    NaN    157.331136  158.575974

Ticker                                       ... DUMMYVEDL4.NS        \
Price              Low       Close   Volume  ...           Low Close
Date                                         ...
2015-01-01  156.608382  172.188904  1116007  ...           NaN   NaN
2015-01-02  161.748301  163.394699   466297  ...           NaN   NaN
2015-01-05  157.853212  159.379135   396192  ...           NaN   NaN
2015-01-06  155.002122  157.371323   201169  ...           NaN   NaN
2015-01-07  154.198974  157.090210   142198  ...           NaN   NaN

Ticker                      DUMMYVEDL3.NS
Price      Adj Close Volume          Open High Low Close Adj Close Volume
Date
2015-01-01       NaN    NaN           NaN  NaN NaN   NaN       NaN    NaN
2015-01-02       NaN    NaN           NaN  NaN NaN   NaN       NaN    NaN
2015-01-05       NaN    NaN           NaN  NaN NaN   NaN       NaN    NaN
2015-01-06       NaN    NaN           NaN  NaN NaN   NaN       NaN    NaN
2015-01-07       NaN    NaN           NaN  NaN NaN   NaN       NaN    NaN

[5 rows x 527 columns]

In [7]:
raw_data["RELIANCE.NS"].head()

Price             Open        High         Low       Close    Volume
Date
2015-01-01  188.784556  189.998667  188.220086  189.125351   2963643
2015-01-02  189.167973  190.861356  188.358571  188.624817   7331366
2015-01-05  188.507680  189.764404  186.185942  186.558701  10103941
2015-01-06  185.312621  185.951626  177.218496  178.091812  18627980
2015-01-07  178.304843  182.927005  178.283544  181.968491  20720312

In [8]:
panel_df = (raw_data.stack(level="Ticker", future_stack=True).reset_index())
panel_df = panel_df.drop(["Adj Close"], axis = 1)
panel_df.head()

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2015-01-01,HDFCLIFE.NS,NaN,NaN,NaN,NaN,NaN
1,2015-01-01,MUTHOOTFIN.NS,157.411502,174.036082,156.608382,172.188904,1116007.0
2,2015-01-01,ADANIENSOL.NS,NaN,NaN,NaN,NaN,NaN
3,2015-01-01,UNITDSPR.NS,544.422864,553.891497,539.526975,551.923340,451940.0
4,2015-01-01,BANKBARODA.NS,180.050846,181.501113,178.825612,180.542603,1756690.0

In [9]:
panel_df["Ticker"].nunique()

104

In [10]:
panel_df.isna().sum()

Price
Date          0
Ticker        0
Open      34966
High      34966
Low       34966
Close     34966
Volume    34966
dtype: int64

In [11]:
panel_df.to_csv(r"C:\Users\naksh\Projects\xgboost_stock_ranking\data\raw\nifty100_panel.csv", index=False)